### ISSUE TITLE
Code Checker

### ISSUE THREAD

**Issue by 69codes** [AjabiOladipupo/simple_shell#1]
Dipo, how will the checker know if our code is compliant, if we are the one choosing the names of the files??

**Comment by AjabiOladipupo** [comment]
Yusuf, The name of the files aren't what is being looked at, the checker is basically going to run various gcc compilers and our codes would be passed based on what was returned. @69codes

**Comment by 69codes** [comment]
Ok, great! Everything is looking good so far!!
